name: Check Code Quality

on: pull_request

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: detekt
        uses: alaegin/Detekt-Action@v1.18.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_level: warning
          reviewdog_reporter: github-pr-review
          detekt_config: config/detekt/detekt.yml
